/*
Package routes GENERATED BY gengo:operator 
DON'T EDIT THIS FILE
*/
package routes

import (
	github_com_go_courier_courier "github.com/go-courier/courier"
	github_com_go_courier_schema_pkg_jsonschema "github.com/go-courier/schema/pkg/jsonschema"
	github_com_go_courier_schema_pkg_openapi "github.com/go-courier/schema/pkg/openapi"
)

func (Cookie) New() github_com_go_courier_courier.Operator {
	return &Cookie{}
}

func (Cookie) OpenAPIOperation(ref func(t string) github_com_go_courier_schema_pkg_jsonschema.Refer) *github_com_go_courier_schema_pkg_openapi.Operation {
	return &(github_com_go_courier_schema_pkg_openapi.Operation{
		OperationObject: github_com_go_courier_schema_pkg_openapi.OperationObject{
			Tags: []string{
				"demo",
			},
			OperationId: "Cookie",
			Parameters: []*github_com_go_courier_schema_pkg_openapi.Parameter{
				&(github_com_go_courier_schema_pkg_openapi.Parameter{
					ParameterObject: github_com_go_courier_schema_pkg_openapi.ParameterObject{
						Name: "token",
						In:   "cookie",
						ParameterCommonObject: github_com_go_courier_schema_pkg_openapi.ParameterCommonObject{
							WithContentOrSchema: github_com_go_courier_schema_pkg_openapi.WithContentOrSchema{
								Schema: &(github_com_go_courier_schema_pkg_jsonschema.Schema{
									SchemaBasic: github_com_go_courier_schema_pkg_jsonschema.SchemaBasic{
										Type: github_com_go_courier_schema_pkg_jsonschema.StringOrArray{
											"string",
										},
									},
									VendorExtensible: github_com_go_courier_schema_pkg_jsonschema.VendorExtensible{
										Extensions: map[string]interface{}{
											"x-go-field-name": "Token",
										},
									},
								}),
							},
						},
					},
				}),
			},
			Responses: github_com_go_courier_schema_pkg_openapi.Responses{
				ResponsesObject: github_com_go_courier_schema_pkg_openapi.ResponsesObject{
					Responses: map[int]*github_com_go_courier_schema_pkg_openapi.Response{
						204: &(github_com_go_courier_schema_pkg_openapi.Response{
							ResponseObject: github_com_go_courier_schema_pkg_openapi.ResponseObject{
								Description: "-",
							},
						}),
					},
				},
			},
		},
	})
}
func (Create) New() github_com_go_courier_courier.Operator {
	return &Create{}
}

func (Create) OpenAPIOperation(ref func(t string) github_com_go_courier_schema_pkg_jsonschema.Refer) *github_com_go_courier_schema_pkg_openapi.Operation {
	return &(github_com_go_courier_schema_pkg_openapi.Operation{
		OperationObject: github_com_go_courier_schema_pkg_openapi.OperationObject{
			Tags: []string{
				"demo",
			},
			OperationId: "Create",
			RequestBody: &(github_com_go_courier_schema_pkg_openapi.RequestBody{
				RequestBodyObject: github_com_go_courier_schema_pkg_openapi.RequestBodyObject{
					Required: true,
					WithContent: github_com_go_courier_schema_pkg_openapi.WithContent{
						Content: map[string]*github_com_go_courier_schema_pkg_openapi.MediaType{
							"application/json": &(github_com_go_courier_schema_pkg_openapi.MediaType{
								MediaTypeObject: github_com_go_courier_schema_pkg_openapi.MediaTypeObject{
									Schema: &(github_com_go_courier_schema_pkg_jsonschema.Schema{
										SchemaBasic: github_com_go_courier_schema_pkg_jsonschema.SchemaBasic{
											AllOf: []*github_com_go_courier_schema_pkg_jsonschema.Schema{
												&(github_com_go_courier_schema_pkg_jsonschema.Schema{
													Reference: github_com_go_courier_schema_pkg_jsonschema.Reference{
														Refer: ref("github.com/go-courier/schema/testdata/routes.Data"),
													},
												}),
												&(github_com_go_courier_schema_pkg_jsonschema.Schema{
													VendorExtensible: github_com_go_courier_schema_pkg_jsonschema.VendorExtensible{
														Extensions: map[string]interface{}{
															"x-go-field-name": "Data",
														},
													},
												}),
											},
										},
									}),
								},
							}),
						},
					},
				},
			}),
			Responses: github_com_go_courier_schema_pkg_openapi.Responses{
				ResponsesObject: github_com_go_courier_schema_pkg_openapi.ResponsesObject{
					Responses: map[int]*github_com_go_courier_schema_pkg_openapi.Response{
						201: &(github_com_go_courier_schema_pkg_openapi.Response{
							ResponseObject: github_com_go_courier_schema_pkg_openapi.ResponseObject{
								Description: "-",
								WithContent: github_com_go_courier_schema_pkg_openapi.WithContent{
									Content: map[string]*github_com_go_courier_schema_pkg_openapi.MediaType{
										"application/json": &(github_com_go_courier_schema_pkg_openapi.MediaType{
											MediaTypeObject: github_com_go_courier_schema_pkg_openapi.MediaTypeObject{
												Schema: &(github_com_go_courier_schema_pkg_jsonschema.Schema{
													Reference: github_com_go_courier_schema_pkg_jsonschema.Reference{
														Refer: ref("github.com/go-courier/schema/testdata/routes.Data"),
													},
												}),
											},
										}),
									},
								},
							},
						}),
					},
				},
			},
		},
	})
}
func (DataProvider) New() github_com_go_courier_courier.Operator {
	return &DataProvider{}
}

func (DataProvider) Path() string {
	return "/:id"
}

func (DataProvider) OpenAPIOperation(ref func(t string) github_com_go_courier_schema_pkg_jsonschema.Refer) *github_com_go_courier_schema_pkg_openapi.Operation {
	return &(github_com_go_courier_schema_pkg_openapi.Operation{
		OperationObject: github_com_go_courier_schema_pkg_openapi.OperationObject{
			Tags: []string{
				"demo",
			},
			OperationId: "DataProvider",
			Parameters: []*github_com_go_courier_schema_pkg_openapi.Parameter{
				&(github_com_go_courier_schema_pkg_openapi.Parameter{
					ParameterObject: github_com_go_courier_schema_pkg_openapi.ParameterObject{
						Name: "id",
						In:   "path",
						ParameterCommonObject: github_com_go_courier_schema_pkg_openapi.ParameterCommonObject{
							Required: true,
							WithContentOrSchema: github_com_go_courier_schema_pkg_openapi.WithContentOrSchema{
								Schema: &(github_com_go_courier_schema_pkg_jsonschema.Schema{
									SchemaBasic: github_com_go_courier_schema_pkg_jsonschema.SchemaBasic{
										Type: github_com_go_courier_schema_pkg_jsonschema.StringOrArray{
											"string",
										},
										SchemaValidation: github_com_go_courier_schema_pkg_jsonschema.SchemaValidation{
											MinLength: func(v uint64) *uint64 { return &v }(6),
										},
									},
									VendorExtensible: github_com_go_courier_schema_pkg_jsonschema.VendorExtensible{
										Extensions: map[string]interface{}{
											"x-go-field-name": "ID",
											"x-tag-validate":  "@string[6,]",
										},
									},
								}),
							},
						},
					},
				}),
			},
			Responses: github_com_go_courier_schema_pkg_openapi.Responses{
				ResponsesObject: github_com_go_courier_schema_pkg_openapi.ResponsesObject{
					Responses: map[int]*github_com_go_courier_schema_pkg_openapi.Response{
						200: &(github_com_go_courier_schema_pkg_openapi.Response{
							ResponseObject: github_com_go_courier_schema_pkg_openapi.ResponseObject{
								Description: "-",
								WithContent: github_com_go_courier_schema_pkg_openapi.WithContent{
									Content: map[string]*github_com_go_courier_schema_pkg_openapi.MediaType{
										"application/json": &(github_com_go_courier_schema_pkg_openapi.MediaType{
											MediaTypeObject: github_com_go_courier_schema_pkg_openapi.MediaTypeObject{
												Schema: &(github_com_go_courier_schema_pkg_jsonschema.Schema{
													Reference: github_com_go_courier_schema_pkg_jsonschema.Reference{
														Refer: ref("github.com/go-courier/schema/testdata/routes.Data"),
													},
												}),
											},
										}),
									},
								},
							},
						}),
					},
				},
			},
		},
	})
}
func (DownloadFile) New() github_com_go_courier_courier.Operator {
	return &DownloadFile{}
}

func (DownloadFile) Path() string {
	return "/files"
}

func (DownloadFile) OpenAPIOperation(ref func(t string) github_com_go_courier_schema_pkg_jsonschema.Refer) *github_com_go_courier_schema_pkg_openapi.Operation {
	return &(github_com_go_courier_schema_pkg_openapi.Operation{
		OperationObject: github_com_go_courier_schema_pkg_openapi.OperationObject{
			Tags: []string{
				"demo",
			},
			OperationId: "DownloadFile",
			Responses: github_com_go_courier_schema_pkg_openapi.Responses{
				ResponsesObject: github_com_go_courier_schema_pkg_openapi.ResponsesObject{
					Responses: map[int]*github_com_go_courier_schema_pkg_openapi.Response{
						200: &(github_com_go_courier_schema_pkg_openapi.Response{
							ResponseObject: github_com_go_courier_schema_pkg_openapi.ResponseObject{
								Description: "-",
								WithContent: github_com_go_courier_schema_pkg_openapi.WithContent{
									Content: map[string]*github_com_go_courier_schema_pkg_openapi.MediaType{
										"application/octet-stream": &(github_com_go_courier_schema_pkg_openapi.MediaType{
											MediaTypeObject: github_com_go_courier_schema_pkg_openapi.MediaTypeObject{
												Schema: &(github_com_go_courier_schema_pkg_jsonschema.Schema{
													Reference: github_com_go_courier_schema_pkg_jsonschema.Reference{
														Refer: ref("github.com/go-courier/httptransport/httpx.Attachment"),
													},
												}),
											},
										}),
									},
								},
							},
						}),
					},
				},
			},
		},
	})
}
func (FormMultipartWithFile) New() github_com_go_courier_courier.Operator {
	return &FormMultipartWithFile{}
}

func (FormMultipartWithFile) Path() string {
	return "/multipart"
}

func (FormMultipartWithFile) OpenAPIOperation(ref func(t string) github_com_go_courier_schema_pkg_jsonschema.Refer) *github_com_go_courier_schema_pkg_openapi.Operation {
	return &(github_com_go_courier_schema_pkg_openapi.Operation{
		OperationObject: github_com_go_courier_schema_pkg_openapi.OperationObject{
			Tags: []string{
				"demo",
			},
			OperationId: "FormMultipartWithFile",
			RequestBody: &(github_com_go_courier_schema_pkg_openapi.RequestBody{
				RequestBodyObject: github_com_go_courier_schema_pkg_openapi.RequestBodyObject{
					Required: true,
					WithContent: github_com_go_courier_schema_pkg_openapi.WithContent{
						Content: map[string]*github_com_go_courier_schema_pkg_openapi.MediaType{
							"multipart/form-data": &(github_com_go_courier_schema_pkg_openapi.MediaType{
								MediaTypeObject: github_com_go_courier_schema_pkg_openapi.MediaTypeObject{
									Schema: &(github_com_go_courier_schema_pkg_jsonschema.Schema{
										SchemaBasic: github_com_go_courier_schema_pkg_jsonschema.SchemaBasic{
											Type: github_com_go_courier_schema_pkg_jsonschema.StringOrArray{
												"object",
											},
											Properties: map[string]*github_com_go_courier_schema_pkg_jsonschema.Schema{
												"data": &(github_com_go_courier_schema_pkg_jsonschema.Schema{
													SchemaBasic: github_com_go_courier_schema_pkg_jsonschema.SchemaBasic{
														AllOf: []*github_com_go_courier_schema_pkg_jsonschema.Schema{
															&(github_com_go_courier_schema_pkg_jsonschema.Schema{
																Reference: github_com_go_courier_schema_pkg_jsonschema.Reference{
																	Refer: ref("github.com/go-courier/schema/testdata/routes.Data"),
																},
															}),
															&(github_com_go_courier_schema_pkg_jsonschema.Schema{
																VendorExtensible: github_com_go_courier_schema_pkg_jsonschema.VendorExtensible{
																	Extensions: map[string]interface{}{
																		"x-go-field-name": "Data",
																	},
																},
															}),
														},
													},
												}),
												"file": &(github_com_go_courier_schema_pkg_jsonschema.Schema{
													SchemaBasic: github_com_go_courier_schema_pkg_jsonschema.SchemaBasic{
														AllOf: []*github_com_go_courier_schema_pkg_jsonschema.Schema{
															&(github_com_go_courier_schema_pkg_jsonschema.Schema{
																Reference: github_com_go_courier_schema_pkg_jsonschema.Reference{
																	Refer: ref("mime/multipart.FileHeader"),
																},
																VendorExtensible: github_com_go_courier_schema_pkg_jsonschema.VendorExtensible{
																	Extensions: map[string]interface{}{
																		"x-go-star-level": 1,
																	},
																},
															}),
															&(github_com_go_courier_schema_pkg_jsonschema.Schema{
																VendorExtensible: github_com_go_courier_schema_pkg_jsonschema.VendorExtensible{
																	Extensions: map[string]interface{}{
																		"x-go-field-name": "File",
																	},
																},
															}),
														},
													},
												}),
												"slice": &(github_com_go_courier_schema_pkg_jsonschema.Schema{
													SchemaBasic: github_com_go_courier_schema_pkg_jsonschema.SchemaBasic{
														Type: github_com_go_courier_schema_pkg_jsonschema.StringOrArray{
															"array",
														},
														Items: &(github_com_go_courier_schema_pkg_jsonschema.SchemaOrArray{
															Schema: &(github_com_go_courier_schema_pkg_jsonschema.Schema{
																SchemaBasic: github_com_go_courier_schema_pkg_jsonschema.SchemaBasic{
																	Type: github_com_go_courier_schema_pkg_jsonschema.StringOrArray{
																		"string",
																	},
																},
															}),
														}),
														Deprecated: true,
													},
													VendorExtensible: github_com_go_courier_schema_pkg_jsonschema.VendorExtensible{
														Extensions: map[string]interface{}{
															"x-go-field-name": "Slice",
														},
													},
												}),
												"string": &(github_com_go_courier_schema_pkg_jsonschema.Schema{
													SchemaBasic: github_com_go_courier_schema_pkg_jsonschema.SchemaBasic{
														Type: github_com_go_courier_schema_pkg_jsonschema.StringOrArray{
															"string",
														},
														Deprecated: true,
													},
													VendorExtensible: github_com_go_courier_schema_pkg_jsonschema.VendorExtensible{
														Extensions: map[string]interface{}{
															"x-go-field-name": "String",
														},
													},
												}),
											},
											SchemaValidation: github_com_go_courier_schema_pkg_jsonschema.SchemaValidation{
												Required: []string{
													"file",
												},
											},
										},
										VendorExtensible: github_com_go_courier_schema_pkg_jsonschema.VendorExtensible{
											Extensions: map[string]interface{}{
												"x-go-field-name": "FormData",
											},
										},
									}),
								},
							}),
						},
					},
				},
			}),
			Responses: github_com_go_courier_schema_pkg_openapi.Responses{
				ResponsesObject: github_com_go_courier_schema_pkg_openapi.ResponsesObject{
					Responses: map[int]*github_com_go_courier_schema_pkg_openapi.Response{
						204: &(github_com_go_courier_schema_pkg_openapi.Response{
							ResponseObject: github_com_go_courier_schema_pkg_openapi.ResponseObject{
								Description: "No Content",
							},
						}),
					},
				},
			},
		},
	})
}
func (FormMultipartWithFiles) New() github_com_go_courier_courier.Operator {
	return &FormMultipartWithFiles{}
}

func (FormMultipartWithFiles) Path() string {
	return "/multipart-with-files"
}

func (FormMultipartWithFiles) OpenAPIOperation(ref func(t string) github_com_go_courier_schema_pkg_jsonschema.Refer) *github_com_go_courier_schema_pkg_openapi.Operation {
	return &(github_com_go_courier_schema_pkg_openapi.Operation{
		OperationObject: github_com_go_courier_schema_pkg_openapi.OperationObject{
			Tags: []string{
				"demo",
			},
			OperationId: "FormMultipartWithFiles",
			RequestBody: &(github_com_go_courier_schema_pkg_openapi.RequestBody{
				RequestBodyObject: github_com_go_courier_schema_pkg_openapi.RequestBodyObject{
					Required: true,
					WithContent: github_com_go_courier_schema_pkg_openapi.WithContent{
						Content: map[string]*github_com_go_courier_schema_pkg_openapi.MediaType{
							"multipart/form-data": &(github_com_go_courier_schema_pkg_openapi.MediaType{
								MediaTypeObject: github_com_go_courier_schema_pkg_openapi.MediaTypeObject{
									Schema: &(github_com_go_courier_schema_pkg_jsonschema.Schema{
										SchemaBasic: github_com_go_courier_schema_pkg_jsonschema.SchemaBasic{
											Type: github_com_go_courier_schema_pkg_jsonschema.StringOrArray{
												"object",
											},
											Properties: map[string]*github_com_go_courier_schema_pkg_jsonschema.Schema{
												"files": &(github_com_go_courier_schema_pkg_jsonschema.Schema{
													SchemaBasic: github_com_go_courier_schema_pkg_jsonschema.SchemaBasic{
														Type: github_com_go_courier_schema_pkg_jsonschema.StringOrArray{
															"array",
														},
														Items: &(github_com_go_courier_schema_pkg_jsonschema.SchemaOrArray{
															Schema: &(github_com_go_courier_schema_pkg_jsonschema.Schema{
																SchemaBasic: github_com_go_courier_schema_pkg_jsonschema.SchemaBasic{
																	Nullable: true,
																},
																Reference: github_com_go_courier_schema_pkg_jsonschema.Reference{
																	Refer: ref("mime/multipart.FileHeader"),
																},
																VendorExtensible: github_com_go_courier_schema_pkg_jsonschema.VendorExtensible{
																	Extensions: map[string]interface{}{
																		"x-go-star-level": 1,
																	},
																},
															}),
														}),
													},
													VendorExtensible: github_com_go_courier_schema_pkg_jsonschema.VendorExtensible{
														Extensions: map[string]interface{}{
															"x-go-field-name": "Files",
														},
													},
												}),
											},
											SchemaValidation: github_com_go_courier_schema_pkg_jsonschema.SchemaValidation{
												Required: []string{
													"files",
												},
											},
										},
										VendorExtensible: github_com_go_courier_schema_pkg_jsonschema.VendorExtensible{
											Extensions: map[string]interface{}{
												"x-go-field-name": "FormData",
											},
										},
									}),
								},
							}),
						},
					},
				},
			}),
			Responses: github_com_go_courier_schema_pkg_openapi.Responses{
				ResponsesObject: github_com_go_courier_schema_pkg_openapi.ResponsesObject{
					Responses: map[int]*github_com_go_courier_schema_pkg_openapi.Response{
						204: &(github_com_go_courier_schema_pkg_openapi.Response{
							ResponseObject: github_com_go_courier_schema_pkg_openapi.ResponseObject{
								Description: "No Content",
							},
						}),
					},
				},
			},
		},
	})
}
func (FormURLEncoded) New() github_com_go_courier_courier.Operator {
	return &FormURLEncoded{}
}

func (FormURLEncoded) Path() string {
	return "/urlencoded"
}

func (FormURLEncoded) OpenAPIOperation(ref func(t string) github_com_go_courier_schema_pkg_jsonschema.Refer) *github_com_go_courier_schema_pkg_openapi.Operation {
	return &(github_com_go_courier_schema_pkg_openapi.Operation{
		OperationObject: github_com_go_courier_schema_pkg_openapi.OperationObject{
			Tags: []string{
				"demo",
			},
			OperationId: "FormURLEncoded",
			RequestBody: &(github_com_go_courier_schema_pkg_openapi.RequestBody{
				RequestBodyObject: github_com_go_courier_schema_pkg_openapi.RequestBodyObject{
					Required: true,
					WithContent: github_com_go_courier_schema_pkg_openapi.WithContent{
						Content: map[string]*github_com_go_courier_schema_pkg_openapi.MediaType{
							"application/x-www-form-urlencoded": &(github_com_go_courier_schema_pkg_openapi.MediaType{
								MediaTypeObject: github_com_go_courier_schema_pkg_openapi.MediaTypeObject{
									Schema: &(github_com_go_courier_schema_pkg_jsonschema.Schema{
										SchemaBasic: github_com_go_courier_schema_pkg_jsonschema.SchemaBasic{
											Type: github_com_go_courier_schema_pkg_jsonschema.StringOrArray{
												"object",
											},
											Properties: map[string]*github_com_go_courier_schema_pkg_jsonschema.Schema{
												"data": &(github_com_go_courier_schema_pkg_jsonschema.Schema{
													SchemaBasic: github_com_go_courier_schema_pkg_jsonschema.SchemaBasic{
														AllOf: []*github_com_go_courier_schema_pkg_jsonschema.Schema{
															&(github_com_go_courier_schema_pkg_jsonschema.Schema{
																Reference: github_com_go_courier_schema_pkg_jsonschema.Reference{
																	Refer: ref("github.com/go-courier/schema/testdata/routes.Data"),
																},
															}),
															&(github_com_go_courier_schema_pkg_jsonschema.Schema{
																VendorExtensible: github_com_go_courier_schema_pkg_jsonschema.VendorExtensible{
																	Extensions: map[string]interface{}{
																		"x-go-field-name": "Data",
																	},
																},
															}),
														},
													},
												}),
												"slice": &(github_com_go_courier_schema_pkg_jsonschema.Schema{
													SchemaBasic: github_com_go_courier_schema_pkg_jsonschema.SchemaBasic{
														Type: github_com_go_courier_schema_pkg_jsonschema.StringOrArray{
															"array",
														},
														Items: &(github_com_go_courier_schema_pkg_jsonschema.SchemaOrArray{
															Schema: &(github_com_go_courier_schema_pkg_jsonschema.Schema{
																SchemaBasic: github_com_go_courier_schema_pkg_jsonschema.SchemaBasic{
																	Type: github_com_go_courier_schema_pkg_jsonschema.StringOrArray{
																		"string",
																	},
																},
															}),
														}),
													},
													VendorExtensible: github_com_go_courier_schema_pkg_jsonschema.VendorExtensible{
														Extensions: map[string]interface{}{
															"x-go-field-name": "Slice",
														},
													},
												}),
												"string": &(github_com_go_courier_schema_pkg_jsonschema.Schema{
													SchemaBasic: github_com_go_courier_schema_pkg_jsonschema.SchemaBasic{
														Type: github_com_go_courier_schema_pkg_jsonschema.StringOrArray{
															"string",
														},
													},
													VendorExtensible: github_com_go_courier_schema_pkg_jsonschema.VendorExtensible{
														Extensions: map[string]interface{}{
															"x-go-field-name": "String",
														},
													},
												}),
											},
											SchemaValidation: github_com_go_courier_schema_pkg_jsonschema.SchemaValidation{
												Required: []string{
													"string",
													"slice",
													"data",
												},
											},
										},
										VendorExtensible: github_com_go_courier_schema_pkg_jsonschema.VendorExtensible{
											Extensions: map[string]interface{}{
												"x-go-field-name": "FormData",
											},
										},
									}),
								},
							}),
						},
					},
				},
			}),
			Responses: github_com_go_courier_schema_pkg_openapi.Responses{
				ResponsesObject: github_com_go_courier_schema_pkg_openapi.ResponsesObject{
					Responses: map[int]*github_com_go_courier_schema_pkg_openapi.Response{
						204: &(github_com_go_courier_schema_pkg_openapi.Response{
							ResponseObject: github_com_go_courier_schema_pkg_openapi.ResponseObject{
								Description: "No Content",
							},
						}),
					},
				},
			},
		},
	})
}
func (GetByID) New() github_com_go_courier_courier.Operator {
	return &GetByID{}
}

func (GetByID) OpenAPIOperation(ref func(t string) github_com_go_courier_schema_pkg_jsonschema.Refer) *github_com_go_courier_schema_pkg_openapi.Operation {
	return &(github_com_go_courier_schema_pkg_openapi.Operation{
		OperationObject: github_com_go_courier_schema_pkg_openapi.OperationObject{
			Tags: []string{
				"demo",
			},
			OperationId: "GetByID",
			Parameters: []*github_com_go_courier_schema_pkg_openapi.Parameter{
				&(github_com_go_courier_schema_pkg_openapi.Parameter{
					ParameterObject: github_com_go_courier_schema_pkg_openapi.ParameterObject{
						Name: "protocol",
						In:   "query",
						ParameterCommonObject: github_com_go_courier_schema_pkg_openapi.ParameterCommonObject{
							WithContentOrSchema: github_com_go_courier_schema_pkg_openapi.WithContentOrSchema{
								Schema: &(github_com_go_courier_schema_pkg_jsonschema.Schema{
									SchemaBasic: github_com_go_courier_schema_pkg_jsonschema.SchemaBasic{
										AllOf: []*github_com_go_courier_schema_pkg_jsonschema.Schema{
											&(github_com_go_courier_schema_pkg_jsonschema.Schema{
												Reference: github_com_go_courier_schema_pkg_jsonschema.Reference{
													Refer: ref("github.com/go-courier/schema/testdata/a.Protocol"),
												},
											}),
											&(github_com_go_courier_schema_pkg_jsonschema.Schema{
												VendorExtensible: github_com_go_courier_schema_pkg_jsonschema.VendorExtensible{
													Extensions: map[string]interface{}{
														"x-go-field-name": "Protocol",
													},
												},
											}),
										},
									},
								}),
							},
						},
					},
				}),
				&(github_com_go_courier_schema_pkg_openapi.Parameter{
					ParameterObject: github_com_go_courier_schema_pkg_openapi.ParameterObject{
						Name: "name",
						In:   "query",
						ParameterCommonObject: github_com_go_courier_schema_pkg_openapi.ParameterCommonObject{
							WithContentOrSchema: github_com_go_courier_schema_pkg_openapi.WithContentOrSchema{
								Schema: &(github_com_go_courier_schema_pkg_jsonschema.Schema{
									SchemaBasic: github_com_go_courier_schema_pkg_jsonschema.SchemaBasic{
										Type: github_com_go_courier_schema_pkg_jsonschema.StringOrArray{
											"string",
										},
									},
									VendorExtensible: github_com_go_courier_schema_pkg_jsonschema.VendorExtensible{
										Extensions: map[string]interface{}{
											"x-go-field-name": "Name",
										},
									},
								}),
							},
						},
					},
				}),
				&(github_com_go_courier_schema_pkg_openapi.Parameter{
					ParameterObject: github_com_go_courier_schema_pkg_openapi.ParameterObject{
						Name: "label",
						In:   "query",
						ParameterCommonObject: github_com_go_courier_schema_pkg_openapi.ParameterCommonObject{
							WithContentOrSchema: github_com_go_courier_schema_pkg_openapi.WithContentOrSchema{
								Schema: &(github_com_go_courier_schema_pkg_jsonschema.Schema{
									SchemaBasic: github_com_go_courier_schema_pkg_jsonschema.SchemaBasic{
										Type: github_com_go_courier_schema_pkg_jsonschema.StringOrArray{
											"array",
										},
										Items: &(github_com_go_courier_schema_pkg_jsonschema.SchemaOrArray{
											Schema: &(github_com_go_courier_schema_pkg_jsonschema.Schema{
												SchemaBasic: github_com_go_courier_schema_pkg_jsonschema.SchemaBasic{
													Type: github_com_go_courier_schema_pkg_jsonschema.StringOrArray{
														"string",
													},
												},
											}),
										}),
									},
									VendorExtensible: github_com_go_courier_schema_pkg_jsonschema.VendorExtensible{
										Extensions: map[string]interface{}{
											"x-go-field-name": "Label",
										},
									},
								}),
							},
						},
					},
				}),
			},
			Responses: github_com_go_courier_schema_pkg_openapi.Responses{
				ResponsesObject: github_com_go_courier_schema_pkg_openapi.ResponsesObject{
					Responses: map[int]*github_com_go_courier_schema_pkg_openapi.Response{
						200: &(github_com_go_courier_schema_pkg_openapi.Response{
							ResponseObject: github_com_go_courier_schema_pkg_openapi.ResponseObject{
								Description: "-",
								WithContent: github_com_go_courier_schema_pkg_openapi.WithContent{
									Content: map[string]*github_com_go_courier_schema_pkg_openapi.MediaType{
										"application/json": &(github_com_go_courier_schema_pkg_openapi.MediaType{
											MediaTypeObject: github_com_go_courier_schema_pkg_openapi.MediaTypeObject{
												Schema: &(github_com_go_courier_schema_pkg_jsonschema.Schema{
													Reference: github_com_go_courier_schema_pkg_jsonschema.Reference{
														Refer: ref("github.com/go-courier/schema/testdata/routes.Data"),
													},
												}),
											},
										}),
									},
								},
							},
						}),
					},
				},
			},
		},
	})
}
func (HealthCheck) New() github_com_go_courier_courier.Operator {
	return &HealthCheck{}
}

func (HealthCheck) OpenAPIOperation(ref func(t string) github_com_go_courier_schema_pkg_jsonschema.Refer) *github_com_go_courier_schema_pkg_openapi.Operation {
	return &(github_com_go_courier_schema_pkg_openapi.Operation{
		OperationObject: github_com_go_courier_schema_pkg_openapi.OperationObject{
			Tags: []string{
				"demo",
			},
			OperationId: "HealthCheck",
			Parameters: []*github_com_go_courier_schema_pkg_openapi.Parameter{
				&(github_com_go_courier_schema_pkg_openapi.Parameter{
					ParameterObject: github_com_go_courier_schema_pkg_openapi.ParameterObject{
						Name: "pullPolicy",
						In:   "query",
						ParameterCommonObject: github_com_go_courier_schema_pkg_openapi.ParameterCommonObject{
							WithContentOrSchema: github_com_go_courier_schema_pkg_openapi.WithContentOrSchema{
								Schema: &(github_com_go_courier_schema_pkg_jsonschema.Schema{
									SchemaBasic: github_com_go_courier_schema_pkg_jsonschema.SchemaBasic{
										AllOf: []*github_com_go_courier_schema_pkg_jsonschema.Schema{
											&(github_com_go_courier_schema_pkg_jsonschema.Schema{
												Reference: github_com_go_courier_schema_pkg_jsonschema.Reference{
													Refer: ref("github.com/go-courier/schema/testdata/b.PullPolicy"),
												},
											}),
											&(github_com_go_courier_schema_pkg_jsonschema.Schema{
												VendorExtensible: github_com_go_courier_schema_pkg_jsonschema.VendorExtensible{
													Extensions: map[string]interface{}{
														"x-go-field-name": "PullPolicy",
													},
												},
											}),
										},
									},
								}),
							},
						},
					},
				}),
			},
			Responses: github_com_go_courier_schema_pkg_openapi.Responses{
				ResponsesObject: github_com_go_courier_schema_pkg_openapi.ResponsesObject{
					Responses: map[int]*github_com_go_courier_schema_pkg_openapi.Response{
						204: &(github_com_go_courier_schema_pkg_openapi.Response{
							ResponseObject: github_com_go_courier_schema_pkg_openapi.ResponseObject{
								Description: "No Content",
							},
						}),
					},
				},
			},
		},
	})
}
func (MustValidAccount) New() github_com_go_courier_courier.Operator {
	return &MustValidAccount{}
}

func (MustValidAccount) OpenAPIOperation(ref func(t string) github_com_go_courier_schema_pkg_jsonschema.Refer) *github_com_go_courier_schema_pkg_openapi.Operation {
	return &(github_com_go_courier_schema_pkg_openapi.Operation{
		OperationObject: github_com_go_courier_schema_pkg_openapi.OperationObject{
			Tags: []string{
				"demo",
			},
			OperationId: "MustValidAccount",
			Parameters: []*github_com_go_courier_schema_pkg_openapi.Parameter{
				&(github_com_go_courier_schema_pkg_openapi.Parameter{
					ParameterObject: github_com_go_courier_schema_pkg_openapi.ParameterObject{
						Name: "Authorization",
						In:   "header",
						ParameterCommonObject: github_com_go_courier_schema_pkg_openapi.ParameterCommonObject{
							WithContentOrSchema: github_com_go_courier_schema_pkg_openapi.WithContentOrSchema{
								Schema: &(github_com_go_courier_schema_pkg_jsonschema.Schema{
									SchemaBasic: github_com_go_courier_schema_pkg_jsonschema.SchemaBasic{
										Type: github_com_go_courier_schema_pkg_jsonschema.StringOrArray{
											"string",
										},
										Description: "Bearer access_token",
									},
									VendorExtensible: github_com_go_courier_schema_pkg_jsonschema.VendorExtensible{
										Extensions: map[string]interface{}{
											"x-go-field-name": "Authorization",
										},
									},
								}),
							},
						},
					},
				}),
				&(github_com_go_courier_schema_pkg_openapi.Parameter{
					ParameterObject: github_com_go_courier_schema_pkg_openapi.ParameterObject{
						Name: "authorization",
						In:   "query",
						ParameterCommonObject: github_com_go_courier_schema_pkg_openapi.ParameterCommonObject{
							WithContentOrSchema: github_com_go_courier_schema_pkg_openapi.WithContentOrSchema{
								Schema: &(github_com_go_courier_schema_pkg_jsonschema.Schema{
									SchemaBasic: github_com_go_courier_schema_pkg_jsonschema.SchemaBasic{
										Type: github_com_go_courier_schema_pkg_jsonschema.StringOrArray{
											"string",
										},
										Description: "Bearer access_token in query",
									},
									VendorExtensible: github_com_go_courier_schema_pkg_jsonschema.VendorExtensible{
										Extensions: map[string]interface{}{
											"x-go-field-name": "AuthorizationInQuery",
										},
									},
								}),
							},
						},
					},
				}),
			},
			Responses: github_com_go_courier_schema_pkg_openapi.Responses{
				ResponsesObject: github_com_go_courier_schema_pkg_openapi.ResponsesObject{
					Responses: map[int]*github_com_go_courier_schema_pkg_openapi.Response{
						200: &(github_com_go_courier_schema_pkg_openapi.Response{
							ResponseObject: github_com_go_courier_schema_pkg_openapi.ResponseObject{
								Description: "-",
								WithContent: github_com_go_courier_schema_pkg_openapi.WithContent{
									Content: map[string]*github_com_go_courier_schema_pkg_openapi.MediaType{
										"application/json": &(github_com_go_courier_schema_pkg_openapi.MediaType{
											MediaTypeObject: github_com_go_courier_schema_pkg_openapi.MediaTypeObject{
												Schema: &(github_com_go_courier_schema_pkg_jsonschema.Schema{
													VendorExtensible: github_com_go_courier_schema_pkg_jsonschema.VendorExtensible{
														Extensions: map[string]interface{}{
															"x-go-vendor-type": "context.Context",
														},
													},
												}),
											},
										}),
									},
								},
							},
						}),
					},
				},
			},
		},
	})
}
func (Proxy) New() github_com_go_courier_courier.Operator {
	return &Proxy{}
}

func (Proxy) OpenAPIOperation(ref func(t string) github_com_go_courier_schema_pkg_jsonschema.Refer) *github_com_go_courier_schema_pkg_openapi.Operation {
	return &(github_com_go_courier_schema_pkg_openapi.Operation{
		OperationObject: github_com_go_courier_schema_pkg_openapi.OperationObject{
			Tags: []string{
				"demo",
			},
			OperationId: "Proxy",
			Responses: github_com_go_courier_schema_pkg_openapi.Responses{
				ResponsesObject: github_com_go_courier_schema_pkg_openapi.ResponsesObject{
					Responses: map[int]*github_com_go_courier_schema_pkg_openapi.Response{
						200: &(github_com_go_courier_schema_pkg_openapi.Response{
							ResponseObject: github_com_go_courier_schema_pkg_openapi.ResponseObject{
								Description: "-",
								WithContent: github_com_go_courier_schema_pkg_openapi.WithContent{
									Content: map[string]*github_com_go_courier_schema_pkg_openapi.MediaType{
										"application/json": &(github_com_go_courier_schema_pkg_openapi.MediaType{
											MediaTypeObject: github_com_go_courier_schema_pkg_openapi.MediaTypeObject{
												Schema: &(github_com_go_courier_schema_pkg_jsonschema.Schema{
													Reference: github_com_go_courier_schema_pkg_jsonschema.Reference{
														Refer: ref("github.com/go-courier/schema/testdata/routes.IpInfo"),
													},
												}),
											},
										}),
									},
								},
							},
						}),
					},
				},
			},
		},
	})
}
func (ProxyV2) New() github_com_go_courier_courier.Operator {
	return &ProxyV2{}
}

func (ProxyV2) OpenAPIOperation(ref func(t string) github_com_go_courier_schema_pkg_jsonschema.Refer) *github_com_go_courier_schema_pkg_openapi.Operation {
	return &(github_com_go_courier_schema_pkg_openapi.Operation{
		OperationObject: github_com_go_courier_schema_pkg_openapi.OperationObject{
			Tags: []string{
				"demo",
			},
			OperationId: "ProxyV2",
			Responses: github_com_go_courier_schema_pkg_openapi.Responses{
				ResponsesObject: github_com_go_courier_schema_pkg_openapi.ResponsesObject{
					Responses: map[int]*github_com_go_courier_schema_pkg_openapi.Response{
						204: &(github_com_go_courier_schema_pkg_openapi.Response{
							ResponseObject: github_com_go_courier_schema_pkg_openapi.ResponseObject{
								Description: "-",
							},
						}),
					},
				},
			},
		},
	})
}
func (Redirect) New() github_com_go_courier_courier.Operator {
	return &Redirect{}
}

func (Redirect) OpenAPIOperation(ref func(t string) github_com_go_courier_schema_pkg_jsonschema.Refer) *github_com_go_courier_schema_pkg_openapi.Operation {
	return &(github_com_go_courier_schema_pkg_openapi.Operation{
		OperationObject: github_com_go_courier_schema_pkg_openapi.OperationObject{
			Tags: []string{
				"demo",
			},
			OperationId: "Redirect",
			Responses: github_com_go_courier_schema_pkg_openapi.Responses{
				ResponsesObject: github_com_go_courier_schema_pkg_openapi.ResponsesObject{
					Responses: map[int]*github_com_go_courier_schema_pkg_openapi.Response{
						302: &(github_com_go_courier_schema_pkg_openapi.Response{
							ResponseObject: github_com_go_courier_schema_pkg_openapi.ResponseObject{
								Description: "Found",
							},
						}),
					},
				},
			},
		},
	})
}
func (RedirectWhenError) New() github_com_go_courier_courier.Operator {
	return &RedirectWhenError{}
}

func (RedirectWhenError) OpenAPIOperation(ref func(t string) github_com_go_courier_schema_pkg_jsonschema.Refer) *github_com_go_courier_schema_pkg_openapi.Operation {
	return &(github_com_go_courier_schema_pkg_openapi.Operation{
		OperationObject: github_com_go_courier_schema_pkg_openapi.OperationObject{
			Tags: []string{
				"demo",
			},
			OperationId: "RedirectWhenError",
			Responses: github_com_go_courier_schema_pkg_openapi.Responses{
				ResponsesObject: github_com_go_courier_schema_pkg_openapi.ResponsesObject{
					Responses: map[int]*github_com_go_courier_schema_pkg_openapi.Response{
						204: &(github_com_go_courier_schema_pkg_openapi.Response{
							ResponseObject: github_com_go_courier_schema_pkg_openapi.ResponseObject{
								Description: "No Content",
							},
						}),
					},
				},
			},
		},
	})
}
func (RemoveByID) New() github_com_go_courier_courier.Operator {
	return &RemoveByID{}
}

func (RemoveByID) OpenAPIOperation(ref func(t string) github_com_go_courier_schema_pkg_jsonschema.Refer) *github_com_go_courier_schema_pkg_openapi.Operation {
	return &(github_com_go_courier_schema_pkg_openapi.Operation{
		OperationObject: github_com_go_courier_schema_pkg_openapi.OperationObject{
			Tags: []string{
				"demo",
			},
			OperationId: "RemoveByID",
			Responses: github_com_go_courier_schema_pkg_openapi.Responses{
				ResponsesObject: github_com_go_courier_schema_pkg_openapi.ResponsesObject{
					Responses: map[int]*github_com_go_courier_schema_pkg_openapi.Response{
						204: &(github_com_go_courier_schema_pkg_openapi.Response{
							ResponseObject: github_com_go_courier_schema_pkg_openapi.ResponseObject{
								Description: "No Content",
							},
						}),
					},
				},
			},
		},
	})
}
func (ShowImage) New() github_com_go_courier_courier.Operator {
	return &ShowImage{}
}

func (ShowImage) Path() string {
	return "/images"
}

func (ShowImage) OpenAPIOperation(ref func(t string) github_com_go_courier_schema_pkg_jsonschema.Refer) *github_com_go_courier_schema_pkg_openapi.Operation {
	return &(github_com_go_courier_schema_pkg_openapi.Operation{
		OperationObject: github_com_go_courier_schema_pkg_openapi.OperationObject{
			Tags: []string{
				"demo",
			},
			OperationId: "ShowImage",
			Responses: github_com_go_courier_schema_pkg_openapi.Responses{
				ResponsesObject: github_com_go_courier_schema_pkg_openapi.ResponsesObject{
					Responses: map[int]*github_com_go_courier_schema_pkg_openapi.Response{
						200: &(github_com_go_courier_schema_pkg_openapi.Response{
							ResponseObject: github_com_go_courier_schema_pkg_openapi.ResponseObject{
								Description: "-",
								WithContent: github_com_go_courier_schema_pkg_openapi.WithContent{
									Content: map[string]*github_com_go_courier_schema_pkg_openapi.MediaType{
										"image/png": &(github_com_go_courier_schema_pkg_openapi.MediaType{
											MediaTypeObject: github_com_go_courier_schema_pkg_openapi.MediaTypeObject{
												Schema: &(github_com_go_courier_schema_pkg_jsonschema.Schema{
													Reference: github_com_go_courier_schema_pkg_jsonschema.Reference{
														Refer: ref("github.com/go-courier/httptransport/httpx.ImagePNG"),
													},
												}),
											},
										}),
									},
								},
							},
						}),
					},
				},
			},
		},
	})
}
func (UpdateByID) New() github_com_go_courier_courier.Operator {
	return &UpdateByID{}
}

func (UpdateByID) OpenAPIOperation(ref func(t string) github_com_go_courier_schema_pkg_jsonschema.Refer) *github_com_go_courier_schema_pkg_openapi.Operation {
	return &(github_com_go_courier_schema_pkg_openapi.Operation{
		OperationObject: github_com_go_courier_schema_pkg_openapi.OperationObject{
			Tags: []string{
				"demo",
			},
			OperationId: "UpdateByID",
			RequestBody: &(github_com_go_courier_schema_pkg_openapi.RequestBody{
				RequestBodyObject: github_com_go_courier_schema_pkg_openapi.RequestBodyObject{
					Required: true,
					WithContent: github_com_go_courier_schema_pkg_openapi.WithContent{
						Content: map[string]*github_com_go_courier_schema_pkg_openapi.MediaType{
							"application/json": &(github_com_go_courier_schema_pkg_openapi.MediaType{
								MediaTypeObject: github_com_go_courier_schema_pkg_openapi.MediaTypeObject{
									Schema: &(github_com_go_courier_schema_pkg_jsonschema.Schema{
										SchemaBasic: github_com_go_courier_schema_pkg_jsonschema.SchemaBasic{
											AllOf: []*github_com_go_courier_schema_pkg_jsonschema.Schema{
												&(github_com_go_courier_schema_pkg_jsonschema.Schema{
													Reference: github_com_go_courier_schema_pkg_jsonschema.Reference{
														Refer: ref("github.com/go-courier/schema/testdata/routes.Data"),
													},
												}),
												&(github_com_go_courier_schema_pkg_jsonschema.Schema{
													VendorExtensible: github_com_go_courier_schema_pkg_jsonschema.VendorExtensible{
														Extensions: map[string]interface{}{
															"x-go-field-name": "Data",
														},
													},
												}),
											},
										},
									}),
								},
							}),
						},
					},
				},
			}),
			Responses: github_com_go_courier_schema_pkg_openapi.Responses{
				ResponsesObject: github_com_go_courier_schema_pkg_openapi.ResponsesObject{
					Responses: map[int]*github_com_go_courier_schema_pkg_openapi.Response{
						204: &(github_com_go_courier_schema_pkg_openapi.Response{
							ResponseObject: github_com_go_courier_schema_pkg_openapi.ResponseObject{
								Description: "No Content",
							},
						}),
					},
				},
			},
		},
	})
}
