/*
Package datalist GENERATED BY gengo:querysql
DON'T EDIT THIS FILE
*/
package datalist

import (
	github_com_go_courier_schema_testdata_db "github.com/go-courier/schema/testdata/db"
	github_com_go_courier_sqlx_v2 "github.com/go-courier/sqlx/v2"
	github_com_go_courier_sqlx_v2_builder "github.com/go-courier/sqlx/v2/builder"
	github_com_go_courier_x_reflect "github.com/go-courier/x/reflect"
)

func (p *OrgParams) ToCondition(d github_com_go_courier_sqlx_v2.TableResolver) github_com_go_courier_sqlx_v2_builder.SqlCondition {
	where := github_com_go_courier_sqlx_v2_builder.EmptyCond()
	mOrg := &github_com_go_courier_schema_testdata_db.Org{}
	tOrg := d.T(mOrg)
	if len(p.OrgID) != 0 {
		where = github_com_go_courier_sqlx_v2_builder.And(
			where,
			tOrg.F(mOrg.FieldKeyOrgID()).
				In(p.OrgID),
		)
	}

	return where
}
func (p *OrgUserParams) ToCondition(d github_com_go_courier_sqlx_v2.TableResolver) github_com_go_courier_sqlx_v2_builder.SqlCondition {
	where := github_com_go_courier_sqlx_v2_builder.EmptyCond()

	return where
}
func (p *UserParams) ToCondition(d github_com_go_courier_sqlx_v2.TableResolver) github_com_go_courier_sqlx_v2_builder.SqlCondition {
	where := github_com_go_courier_sqlx_v2_builder.EmptyCond()
	mUser := &github_com_go_courier_schema_testdata_db.User{}
	tUser := d.T(mUser)
	if len(p.Name) != 0 {
		where = github_com_go_courier_sqlx_v2_builder.And(
			where,
			tUser.F(mUser.FieldKeyName()).
				In(p.Name),
		)
	}
	if len(p.Username) != 0 {
		where = github_com_go_courier_sqlx_v2_builder.And(
			where,
			tUser.F(mUser.FieldKeyUsername()).
				In(p.Username),
		)
	}
	if len(p.Nickname) != 0 {
		where = github_com_go_courier_sqlx_v2_builder.And(
			where,
			tUser.F(mUser.FieldKeyNickname()).
				In(p.Nickname),
		)
	}
	if !github_com_go_courier_x_reflect.IsEmptyValue(p.UserCreatedAt) {
		where = github_com_go_courier_sqlx_v2_builder.And(
			where,
			tUser.F(mUser.FieldKeyCreatedAt()).
				In(p.UserCreatedAt),
		)
	}

	return where
}
