/*
Package db GENERATED BY gengo:table 
DON'T EDIT THIS FILE
*/
package db

import (
	github_com_go_courier_sqlx_v2_builder "github.com/go-courier/sqlx/v2/builder"
)

func (Org) TableName() string {
	return "t_org"
}

func (Org) Primary() []string {
	return []string{
		"ID",
	}
}

func (Org) TableDescription() []string {
	return []string{
		"organization",
	}
}

func (Org) Comments() map[string]string {
	return map[string]string{
		"UserID": "关联用户",
	}
}

func (Org) ColDescriptions() map[string][]string {
	return map[string][]string{
		"UserID": []string{
			"xxxxx",
		},
	}
}

func (Org) ColRelations() map[string][]string {
	return map[string][]string{
		"UserID": []string{
			"User",
			"ID",
		},
	}
}
func (User) TableName() string {
	return "t_user"
}

func (User) Primary() []string {
	return []string{
		"ID",
	}
}

func (User) Indexes() github_com_go_courier_sqlx_v2_builder.Indexes {
	return github_com_go_courier_sqlx_v2_builder.Indexes{
		"i_geom/SPATIAL": []string{
			"Geom",
		},
		"i_nickname/BTREE": []string{
			"Nickname",
		},
		"i_username": []string{
			"Username",
		},
	}
}

func (User) UniqueIndexes() github_com_go_courier_sqlx_v2_builder.Indexes {
	return github_com_go_courier_sqlx_v2_builder.Indexes{
		"i_name": []string{
			"Name",
		},
	}
}

func (User) Comments() map[string]string {
	return map[string]string{
		"Name": "姓名",
	}
}
