/*
Package db GENERATED BY gengo:tablemodel 
DON'T EDIT THIS FILE
*/
package db

import (
	github_com_go_courier_sqlx_v2_builder "github.com/go-courier/sqlx/v2/builder"
)

func (v *Org) ColumnReceivers() map[string]interface{} {
	return map[string]interface{}{
		"f_org_id": &v.OrgID,
		"f_name":   &v.Name,
	}
}
func (Org) TableName() string {
	return "t_org"
}

func (Org) UniqueIndexes() github_com_go_courier_sqlx_v2_builder.Indexes {
	return github_com_go_courier_sqlx_v2_builder.Indexes{
		"i_org_id": []string{
			"OrgID",
		},
	}
}
func (Org) FieldKeyOrgID() string {
	return "OrgID"
}
func (Org) FieldKeyName() string {
	return "Name"
}
func (v *OrgUser) ColumnReceivers() map[string]interface{} {
	return map[string]interface{}{
		"f_id":      &v.ID,
		"f_org_id":  &v.OrgID,
		"f_user_id": &v.UserID,
	}
}
func (OrgUser) TableName() string {
	return "t_org_user"
}

func (OrgUser) Primary() []string {
	return []string{
		"ID",
	}
}

func (OrgUser) Indexes() github_com_go_courier_sqlx_v2_builder.Indexes {
	return github_com_go_courier_sqlx_v2_builder.Indexes{
		"i_org_id": []string{
			"OrgID",
		},
		"i_user_id": []string{
			"UserID",
		},
	}
}

func (OrgUser) FieldKeyID() string {
	return "ID"
}
func (OrgUser) FieldKeyOrgID() string {
	return "OrgID"
}
func (OrgUser) FieldKeyUserID() string {
	return "UserID"
}
func (v *User) ColumnReceivers() map[string]interface{} {
	return map[string]interface{}{
		"f_user_id":    &v.UserID,
		"f_name":       &v.Name,
		"f_username":   &v.Username,
		"f_nickname":   &v.Nickname,
		"f_gender":     &v.Gender,
		"f_boolean":    &v.Boolean,
		"f_geom":       &v.Geom,
		"f_created_at": &v.CreatedAt,
		"f_updated_at": &v.UpdatedAt,
		"f_deleted_at": &v.DeletedAt,
	}
}
func (User) TableName() string {
	return "t_user"
}

func (User) Indexes() github_com_go_courier_sqlx_v2_builder.Indexes {
	return github_com_go_courier_sqlx_v2_builder.Indexes{
		"i_geom/SPATIAL": []string{
			"Geom",
		},
		"i_nickname/BTREE": []string{
			"Nickname",
		},
		"i_username": []string{
			"Username",
		},
	}
}

func (User) UniqueIndexes() github_com_go_courier_sqlx_v2_builder.Indexes {
	return github_com_go_courier_sqlx_v2_builder.Indexes{
		"i_name": []string{
			"Name",
		},
		"i_user_id": []string{
			"UserID",
		},
	}
}
func (User) FieldKeyUserID() string {
	return "UserID"
}
func (User) FieldKeyName() string {
	return "Name"
}
func (User) FieldKeyUsername() string {
	return "Username"
}
func (User) FieldKeyNickname() string {
	return "Nickname"
}
func (User) FieldKeyGender() string {
	return "Gender"
}
func (User) FieldKeyBoolean() string {
	return "Boolean"
}
func (User) FieldKeyGeom() string {
	return "Geom"
}
func (User) FieldKeyCreatedAt() string {
	return "CreatedAt"
}
func (User) FieldKeyUpdatedAt() string {
	return "UpdatedAt"
}
func (User) FieldKeyDeletedAt() string {
	return "DeletedAt"
}
